### ISSUE TITLE
[Site]: 中文 博客博客博客博客博客 blog bug

### ISSUE THREAD

**Issue by Chever-John** [iresty/iresty.github.io#1042]
### Current State

**Description of the current state/issue**:
If you keep switching back and forth between the English and Chinese blog dropdown options. this bug will appear. In fact, I found this bug by accident because of the network.

**Link to the page**:
https://apisix.apache.org/blog/2022/03/01/apisix-integration-public-api-plugin/#initial-knowledge-about-public-api

**Screenshots (if relevant)**:
<img width="367" alt="image" src="https://user-images.githubusercontent.com/43690894/164043327-99bf19e7-69c8-4045-8087-e504ecfe5c8d.png">

### Desired State

**Description of the change you are proposing**:
Of course I want to visit a normal website!

### Would you like to fix this issue?

No. Please assign another contributor

**Comment by SkyeYoung** [comment]
That's what I said to zhiyuan in #1041
> After discussion with @SkyeYoung, the logic is very complicated, so I just added an issue here. Logic: [https://github.com/apache/apisix-website/blob/master/website/src/clientModules/amend-lang-switch.js](https://github.com/apache/apisix-website/blob/master/website/src/clientModules/amend-lang-switch.js?rgh-link-date=2022-04-19T03%3A26%3A38Z)

We have no way to accurately control the timing of modifying this button, so some strange problems may occur if there is a poor network condition.

I can try to make some improvements, but the problems caused by the network can never be solved.

And also I can't reproduce the problem. Please describe the exact reproduction steps.

**Comment by Chever-John** [comment]
Okay, it is a bug that can't be fixed, identification is complete.

**Comment by SkyeYoung** [comment]
@Chever-John yes, I think the issue should be closed, because there is no problem with the logic of the code. But you can track some improvements in #1041.

cc @juzhiyuan

**Comment by Chever-John** [comment]
Hi, let me add more info about this issue in order for developer to learn more about it and make a suitable explanation.

My reproduction process:

1. open a [blog](https://apisix.apache.org/zh/blog/2021/11/30/use-apisix-ingress-in-kubesphere/#%E6%9A%B4%E9%9C%B2%E7%9B%B8%E5%85%B3-prometheus-%E7%9B%91%E6%8E%A7%E6%8C%87%E6%A0%87)(now it was "简体中文 blog" state) and try to read it.
2. Then i try to switch this page from "简体中文 blog" to "English blog" and I did it.
3. After that I turned on Google's translation function.
4. Now you can get this bug.

<img width="223" alt="image" src="https://user-images.githubusercontent.com/43690894/164127914-57a2f550-3ec5-4b46-a1f9-4a8dd9bbc269.png">

**Comment by SkyeYoung** [comment]
> * After that I turned on Google's translation function.

In fact, the problem was caused by the Google Translate plugin in your computer. Since you were constantly refreshing, requests for translations were being sent constantly, and it just so happened that the code to add the _blog_ suffix was being executed after the translation (the current code detects if there is a _blog_ suffix to determine whether to add). Therefore, this issue will not be fixed until after some improvements are made to #1041
