### ISSUE TITLE
[Docs]: Let's add a linter to detect 404 link

### ISSUE THREAD

**Issue by spacewander** [iresty/iresty.github.io#1047]
### Current State

**Description of the current state/issue**:
People keep reporting the broken links during the refactor of the documentation.

**Link to the page**:

**Screenshots (if relevant)**:

### Desired State

**Description of the change you are proposing**:
It would be greater if we can add a linter to detect the broken links.

### Would you like to fix this issue?

No. Please assign another contributor

**Comment by SkyeYoung** [comment]
In fact, we already have one https://github.com/apache/apisix-website/actions/workflows/link-check.yml.

But in website we can only ensure that there are no broken links in the blog pages. The documentation of other projects needs to be checked by each project itself. We shouldn't solve the problems of other repositories in the website repository.

**Comment by spacewander** [comment]
It is suggested to add linter in the website to solve this problem:
https://github.com/apache/apisix/pull/6881#discussion_r853765224

CC @juzhiyuan

**Comment by SkyeYoung** [comment]
I think this issue can be closed since we already have a link checker, and the question of whether there is a problem with the link checker in operation should be discussed in a separate issue.

cc @navendu-pottekkat

**Comment by pottekkat** [comment]
@SkyeYoung Yes. That is correct. However, does the current link checker check for cases where links are on other repos?

Since all the files from all the repos are pulled in `apisix-website` during build, links referencing other repos should work for the link checker in this repository.

For docs changes in the other repos, we can't however check this as we do not build the website in those repos. Only static link checking will work and it will fail in the case where we refer documents in other repos.

Does this make sense?

**Comment by SkyeYoung** [comment]
@navendu-pottekkat Hi, I created a new issue to discuss current problems of link checker. So, sorry, I moved the reply there， you can check https://github.com/apache/apisix-website/issues/1055#issuecomment-1108703660
