### ISSUE TITLE
[Site]: route /plugins, has styled error

### ISSUE THREAD

**Issue by barchielAbyss** [iresty/iresty.github.io#1107]
### Current State

**Description of the current state/issue**:
the sidebar style is `position: fixed`, When the page is scrolled to the bottom, the sidebar will overlap with the footer

**Link to the page**:
https://apisix.apache.org/plugins/

**Screenshots (if relevant)**:
<img width="1379" alt="image" src="https://user-images.githubusercontent.com/23497322/169575997-5d821025-572a-4ae5-8ecd-f42011d7b015.png">

### Desired State

**Description of the change you are proposing**:

use Affix type, dynamically calculate the height of parent elements instead of the whole document

### Would you like to fix this issue?

Yes! Count me in

**Comment by SkyeYoung** [comment]
![image](https://user-images.githubusercontent.com/48400568/169652586-39cc1f3c-c667-428a-8ebf-cc6f3f6aa85d.png)

Looks like a styling error, the image above is what it looks like in my monitor, maybe it can be fixed by just changing the css rules?

You can fix it the way you want, ping me if you run into problems.😊
