### ISSUE TITLE
[Site]: Pls HELP me in this issue

### ISSUE THREAD

**Issue by sanjayk0508** [iresty/iresty.github.io#1273]
### Current State

i have been trying to clone the website in the local IDE. But it shows something like this,

![Screenshot (31)](https://user-images.githubusercontent.com/102804548/183252077-30651775-973e-4bc9-bbb0-bb5cbb7d11b6.png)

I tried everything, but still not working. I'm quite new to open source, pls help me out in this -( i want to work the UI of the website)

By the way this is how my terminal looks like
![Screenshot (32)](https://user-images.githubusercontent.com/102804548/183252198-2639f734-23b6-41de-9f4e-2eff067938f0.png)

### Desired State

**Description of the change you are proposing**:

**Comment by SkyeYoung** [comment]
Sorry for taking so long to reply to you, can you please tell me what are the commands you use?

It looks like you are running is the English blog part with `yarn start:blog:en`? Since our website has been divided into multiple sections, it is normal to behave this way.

If the style you want to modify is:

* for the blogs, please visit `localhost:3000/blog`.
* for the docs, run `yarn start:doc` and visit `localhost:3000/docs`.
* for other pages (home\download\...), run `yarn start:website`.

**Comment by sanjayk0508** [comment]
The commands i used were-

1.`yarn`
2.` yarn sync-doc `
  `yarn generate-repos-info `
 ` yarn generate-picked-posts`
3.` yarn start:doc`

and i guess mistakenly i accessed the docs, where as i wanted to access the home page website.
Any ways i ran `yarn start:website` and it worked, Thank you so much for your help.
