### ISSUE TITLE
[Site]: https://apisix.apache.org is empty on Opera（Macbook Pro M1）

### ISSUE THREAD

**Issue by ctyytc** [iresty/iresty.github.io#1372]
### Current State

**Description of the current state/issue**:
When I use Opera Browser, Home page of https://apisix.apache.org can't see anything. Same time, other browser is OK.
<img width="588" alt="image" src="https://user-images.githubusercontent.com/413886/197476838-895e2a50-8576-496a-8d73-4c64992e0bfa.png">
<img width="580" alt="image" src="https://user-images.githubusercontent.com/413886/197476910-cf8bd9c6-3f68-4fb2-8158-61ac6cc2772d.png">

**Link to the page**:
https://apisix.apache.org

**Screenshots (if relevant)**:
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/413886/197476058-2f08c8ec-d379-4627-bcc8-ad91fdaf8871.png">

### Desired State

**Description of the change you are proposing**:

**Comment by guitu168** [comment]
Hi, can you use Google Chrome browser？

**Comment by ctyytc** [comment]
> Hi, can you use Google Chrome browser？

I have Chrome, but my main browser is Opera, That's why I'm asking this question.

**Comment by guitu168** [comment]
Can you check out this issue? cc @SkyeYoung

**Comment by SkyeYoung** [comment]
This is because this section on the right side of the home page requires the use of WebGL.

![image](https://user-images.githubusercontent.com/48400568/197787970-1df2beea-9c80-4073-bce5-d35508b4eac1.png)

But I don't really know why this is happening, especially after I read https://caniuse.com/?search=webgl. It looks like Opera already supports this feature.

![image](https://user-images.githubusercontent.com/48400568/197789097-3e06a83b-d423-4dd2-b1e1-1d3c56536c20.png)

Since I am not using Opera, can you help me to confirm if it has some options to disable the use of WebGL?

(Also, since it's using Chromium as the kernel, I don't think there's much reason to use Opera anymore in this day and age ......)

**Comment by ctyytc** [comment]
> This is because this section on the right side of the home page requires the use of WebGL.
> 
> ![image](https://user-images.githubusercontent.com/48400568/197787970-1df2beea-9c80-4073-bce5-d35508b4eac1.png)
> 
> But I don't really know why this is happening, especially after I read https://caniuse.com/?search=webgl. It looks like Opera already supports this feature.
> 
> ![image](https://user-images.githubusercontent.com/48400568/197789097-3e06a83b-d423-4dd2-b1e1-1d3c56536c20.png)
> 
> Since I am not using Opera, can you help me to confirm if it has some options to disable the use of WebGL?
> 
> (Also, since it's using Chromium as the kernel, I don't think there's much reason to use Opera anymore in this day and age ......)

Thanks for reply, When I turn on "Settings->System->Use hardware acceleration when available", every thing OK.
