### ISSUE TITLE
grpc无法正确调用

### ISSUE THREAD

**Issue by foursunZero** [iresty/iresty.github.io#1585]
### Current State

按照官网给出的实力进行grpc代理，调用时出现以下错误，无法正确调用

![image](https://github.com/apache/apisix-website/assets/94374926/b924d0cf-965c-421e-bf7a-49b9d6603b53)
官网地址https://apisix.apache.org/zh/docs/ingress-controller/tutorials/proxy-grpc-service/#prerequisites

**Comment by yzeng25** [comment]
Hello @shilingna , you should log this issue in https://github.com/apache/apisix/issues, as it contains all the docs for apisix projects.

Please record the issue in English with more descriptions and details(i.e. apisix versions, OS versions, steps to reproduce) there. You can close this issue here afterwards.

**Comment by yzeng25** [comment]
As explained in previous comment, please create another issue in the other repo, close this issue.
