### ISSUE TITLE
Add a online meetup page

### ISSUE THREAD

**Issue by takumi913** [iresty/iresty.github.io#875]
**Actual Behaviour**

Currently, Apache APISIX don't have meetup page, if someone want to participate online meetup, they only receive invitation from mailling list.

 

**Expected Behaviour**

A better way is let users subscribe meetup link, just like https://konghq.com/online-meetups/

 

**Steps to reproduce it**

 

**Screenshots of the issue**

 

**Would you like to work on the issue?**

**Comment by rinkydevi** [comment]
hey @1502shivam-singh , i would like to work in this issue, also @zaunist can u please help a bit more on how to proceed in this

**Comment by takumi913** [comment]
cc @guoqqqi

**Comment by 1502shivam-singh** [comment]
> hey @1502shivam-singh , i would like to work in this issue, also @zaunist can u please help a bit more on how to proceed in this

I would prefer a discussion first on how to move forward with this, highlighting the problems faced at the moment and putting forward some ideas that can solve them. Later we can talk about wireframes, development etc.

To other contributors, please feel free to add suggestions and comments on this.

**Comment by juzhiyuan** [comment]
Also, I would like to have more feedback from community, including @Boburmirzo, @avinal and @Anita-ihuman 😄

**Comment by Boburmirzo** [comment]
Hi Contributors,

Recently, I also brought this idea and included the task to remind. 

Of course,  it would be nice if we had this kind of sub-page under the community section similar to VueJs did where the community can track all events:

https://events.vuejs.org/

And most of us will support it.

**Problem:**

Currently, I am sharing a list of events in excel format and sharing it on Slack if someone would like to participate in the conference. You can refer to my previous post on slack. 

https://the-asf.slack.com/files/T4S1WH2J3/F034T5V9FF0?origin_team=T4S1WH2J3

The issue is it is not available on the website and difficult to follow. 

**Proposed solution**

I found a better place for it and publish events information simply in .md file format under the new label Events and as a subpage for Community.

![image](https://user-images.githubusercontent.com/14247607/156928480-caa1baed-8d99-481f-a819-1cd8f4fa9397.png)

https://apisix.apache.org/docs/general/community

The implementation is also very straightforward. Then everyone can create a PR if new events come up.

We might have 3 types of events under Community -> Event -> 

1. Conferences
2. Events
3. Workshops

if you would like to work on it, ping me directly on Slack [rinkydevi](https://github.com/rinkydevi), so I can give more details.

Sample, .md file will look this:

https://github.com/vuejs/events/tree/main/src/conferences

**Comment by Anita-ihuman** [comment]
@Boburmirzo, that's right. The architecture plan we drafted looks exactly like that. Except instead of community/events, we might have general/events.

According to how the website is now. (https://apisix.apache.org/docs/general/community)

**Comment by Boburmirzo** [comment]
@Anita-ihuman 

Good, according to architecture then, we can have general/events too with 3 sublabels (Conferences, Events, Workshops)  

Is it fine to work with the changes from now on? 

If yes, @[rinkydevi](https://github.com/rinkydevi) help us to do it.

**Comment by Anita-ihuman** [comment]
Yea it’s good to work on the changes now.

**Comment by guoqqqi** [comment]
I think we could start by adding an online meeting module to the community, as it is part of our community communication 
https://apisix.apache.org/docs/general/community/,
If we were to add an online meetup page, I think we could put in some other learning materials like youtube, Bili Bili etc, like a video library. Just a few of my thoughts~ Let's see other comments 😄

**Comment by Boburmirzo** [comment]
> I think we could start by adding an online meeting module to the community, as it is part of our community communication https://apisix.apache.org/docs/general/community/, If we were to add an online meetup page, I think we could put in some other learning materials like youtube, Bili Bili etc, like a video library. Just a few of my thoughts~ Let's see other comments 😄

Agree, I also saw in many examples Event is under Community path and yeah, new YouTube tutorials I am working on can also go to video tutorials.

**Comment by takumi913** [comment]
> I think we could start by adding an online meeting module to the community, as it is part of our community communication https://apisix.apache.org/docs/general/community/, If we were to add an online meetup page, I think we could put in some other learning materials like youtube, Bili Bili etc, like a video library. Just a few of my thoughts~ Let's see other comments 😄

Agree.

**Comment by Boburmirzo** [comment]
I am sharing here information about events and speakers which can be published on the website:

The list of upcoming events:
https://docs.google.com/spreadsheets/d/1FhEWlot9W-3BU_oEVUVUhundHVGwaHelm6n54NLsihE/edit#gid=2036155589

Also, I and Nicolas mainly are participating in the conferences, we would like to have this information on the website too.
Currently, you can track online at this link:

The list of talks:
https://docs.google.com/spreadsheets/d/1OmPpnJdm3e9_lxHfNt9htameZMUYUq9xy179MgXxmDo/edit#gid=0

**Comment by Boburmirzo** [comment]
Hi, 

So, did we decide to processed this proposal for the event's webpage? @zaunist, @rinkydevi @juzhiyuan @guoqqqi @1502shivam-singh 

In the beginning, we can simply take the way I provided above.

Some students and contributors are really interested to see it.

**Comment by juzhiyuan** [comment]
Hi @Boburmirzo, could you provide a prototype or UI? then @guoqqqi will help to implement it.

**Comment by Boburmirzo** [comment]
@juzhiyuan Do we really need a prototype UI for it? : )

Since the idea is very simple and adding a couple of .md files.

We can publish events information simply in .md file format under the new label Events and as a subpage for Community.

![image](https://user-images.githubusercontent.com/14247607/156928480-caa1baed-8d99-481f-a819-1cd8f4fa9397.png)

https://apisix.apache.org/docs/general/community

We might have 3 types of events under Community -> Event -> 

1. Conferences
2. Events
3. Workshops

.Md file design should look like this:

https://github.com/vuejs/events/tree/main/src/conferences

Just let me know if it is not enough information, I can draw something. @guoqqqi

I need only the template in place, later I can update them frequently with recent event information.

**Comment by juzhiyuan** [comment]
```
We might have 3 types of events under Community -> Event ->

1. Conferences
2. Events
3. Workshops
```

It's OK for me, straightforward and easy to do this. 🎉 

@Boburmirzo Could you please put a markdown file with preferred structure content under here directly and send a PR? https://github.com/apache/apisix-website/tree/master/website/docs/general?

**Comment by Boburmirzo** [comment]
@juzhiyuan Sure, you can assign the task to me and I will take care of the rest.

**Comment by juzhiyuan** [comment]
Thanks Bobur!

**Comment by Boburmirzo** [comment]
@zaunist, @rinkydevi @juzhiyuan @guoqqqi @1502shivam-singh 
 
 PR is created for it.
