### ISSUE TITLE
[Site]: Why the website have to rebuild everyday?

### ISSUE THREAD

**Issue by SkyeYoung** [iresty/iresty.github.io#964]
### Current State

**Description of the current state/issue**:
As the title says.

**Link to the page**:

**Screenshots (if relevant)**:

### Desired State

**Description of the change you are proposing**:

**Comment by SkyeYoung** [comment]
@juzhiyuan

**Comment by juzhiyuan** [comment]
This is a historical question that we discussed many times in 2020: do we need to put all project documentation in the apisix-website repository, or do we maintain each repository separately? The conclusion was to maintain each repository separately but keep a unified directory structure, that's why we will notice some directories like `{repo}/docs/{language}/xxx`.

Under the current directory structure, the documentation website needs to fetch the original document content from each repository and build it. To ensure that the documentation station is up to date, a daily build is chosen, that's why we have a CRON job: https://github.com/apache/apisix-website/blob/master/.github/workflows/deploy.yml#L14

Now that there is more and more documentation content in each repository, it is possible to build only the last few versions, and historical documentation can be archived to Netlify's service, refer to Docusaurus https://docusaurus.io/docs.

![image](https://user-images.githubusercontent.com/2106987/159391526-8ff3daf6-7f2e-4aff-b83c-2c3de7a344fb.png)

**Comment by SkyeYoung** [comment]
> To ensure that the documentation station is up to date, a daily build is chosen,

Why not use git hooks to trigger the build?

**Comment by juzhiyuan** [comment]
1. No time.
2. Those repos are under the ASF, no token.
3. There have plenty of PRs in other repos, they will trigger building many times.

**Comment by SkyeYoung** [comment]
> * No time.
> * Those repos are under the ASF, no token.
> * There have plenty of PRs in other repos, they will trigger building many times.

Ok, I know. Thx ASF.
